### PR TITLE
Merge Client-side auto-reconnect implementation into auto-reconnect

### PR DESCRIPTION
**Pull request by Justsnoopy30**
Title says it all.

### CODE REVIEW

**Comment by player-4** [comment]
@Justsnoopy30, please fix your merge conflicts

**Comment by Justsnoopy30** [comment]
No longer has merge conflicts.

**Comment by Guergeiro** [comment]
Hi @Justsnoopy30, please remove the lines associated with merge conflicts...

**Comment by player-4** [comment]
@Justsnoopy30 , I recommend that you pull down the base branch again and implement your changes on a fresh copy of the base branch. The base branch in this context is `auto-reconnect`. You still have merge conflict lines and after speaking to you in Discord, it seems that you still need to learn how Git works. Here are some steps for you to follow:

```
git checkout auto-reconnect
git pull
git checkout -b "new-client-side-auto-reconnect-branch"
```

Once you've done that, implement your changes and make another PR. Please contribute the proper way. Don't treat this project like it's a personal project where changes only affect you.

**Pull request closed without merging**
