### PR TITLE
make client.js a module

### PR DESCRIPTION
**Pull request by crookse**

### CODE REVIEW

**Comment by crookse** [comment]
btw @Justsnoopy30, your PR had some formatting issues with the code blocks

Screen Shot 2020-06-20 at 19 42 53

**Comment by Justsnoopy30** [comment]
> btw @Justsnoopy30, your PR had some formatting issues with the code blocks
> 
> Screen Shot 2020-06-20 at 19 42 53

Oh yeah... to fix that I would have to remove all the indentation and make that section hard to read again. Do you think it's worth the extra maintenance cost?

**Comment by crookse** [comment]
> Oh yeah... to fix that I would have to remove all the indentation and make that section hard to read again. Do you think it's worth the extra maintenance cost?

yea. what i care about more in this context is what the developer sees. drashland is documentation-driven, so any documentation in drash should be clean.

**Comment by Justsnoopy30** [comment]
> > Oh yeah... to fix that I would have to remove all the indentation and make that section hard to read again. Do you think it's worth the extra maintenance cost?
> 
> yea. what i care about more in this context is what the developer sees. drashland is documentation-driven, so any documentation in drash should be clean.

Okay, will fix.

**Pull request merged**
